<?php

use Lib\MainLayout;
use Lib\Request;

MainLayout::$title = !empty(MainLayout::$title) ? MainLayout::$title : 'Create Prisma PHP App';
MainLayout::$description = !empty(MainLayout::$description) ? MainLayout::$description : 'Generated by create Prisma PHP App';

?>

<html lang="en">

<head>
    <!-- Dynamic Meta Tags -->
    <link rel="icon" href="<?= Request::baseUrl; ?>/favicon.ico" type="image/x-icon" sizes="16x16" />
    <!-- Dynamic Header Scripts -->
    <link href="<?= Request::baseUrl; ?>/css/styles.css" rel="stylesheet" /> 
    <script src="<?= Request::baseUrl; ?>/js/morphdom-umd.min.js"></script>
    <script src="<?= Request::baseUrl; ?>/js/json5.min.js"></script>
    <script src="<?= Request::baseUrl; ?>/js/index.js"></script>
</head>

<body pp-component="app" class="bg-slate-950 text-slate-100 font-sans selection:bg-primary-400/30">
    <?= MainLayout::$children; ?>
    <!-- Dynamic Footer Scripts -->
</body>

</html>